### PR TITLE
Feature/par 36 sim convert agent implementation

### PR DESCRIPTION
**Pull request by Mqqrc**
Converted the flight booking agent file.

IMPORTANT Notes:
1. Of course these imports aren't working yet as the mocks are needed so I just created temporary variables for that:
image
image

2. I changed some small things in custom agent config, shouldn't make any difference, it was just the order of the parameters in the constructor of some classes
3. Important question: This is a screenshot of the python implementation, I was not sure if the stuff in brackets {} should be a reference to the according variable or if it should be plain text inside of the string, what do you think? I considered it as plain text but I am wrong pretty sure.

image
image

### CODE REVIEW

**Review by weirdkey — DISMISSED** [review]

**Comment by weirdkey** [comment]
Please change the branch from main to development. Despite that, everything looks fine 🚀

**Comment by ardaakcabuyuk** [comment]
About your question:

I believe that the brackets are string literals, and they're formatted with the configs later. So, actually interpreting them as strings seems like the correct approach here. We can also follow the same strategy with the following code snippet.
```
return SystemMessagePromptTemplate.from_template(self.config.system_prompt_template).format(
            role=self.config.role,
            persona=self.config.persona,
            conversation_strategy=self.config.conversation_strategy,
            tasks=json.dumps(self.config.tasks, indent=2),
            current_date=datetime.datetime.now().strftime("%d-%b-%Y"),
            formatted_tools=json.dumps(tool_descriptions, indent=2),
        )
```

Besides that, thank you for your effort! 🚀

**Comment by ardaakcabuyuk** [comment]
What I would ask you to do in the following steps is to follow the Typescript naming conventions. I see that conversion from Python ends up with a snake_case naming, but I believe that it would be better to be consistent about that.

For files:
file.[type].ts

For functions, variables, parameters, etc.:
camelCasedName

For classes:
ClassName

**Review by weirdkey — APPROVED** [review]
Looks fine for me

**Pull request merged**
